// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCErP8SBz4ExEvmv9kqCowbJCcAuF20q40',
    appId: '1:431969184661:web:cdc33bf93f05535f19a49c',
    messagingSenderId: '431969184661',
    projectId: 'scanly-a1214',
    authDomain: 'scanly-a1214.firebaseapp.com',
    storageBucket: 'scanly-a1214.firebasestorage.app',
    measurementId: 'G-800V6RGTML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4ehE0r6DR8rQifo4nDSvG0kEcXkAJpg',
    appId: '1:431969184661:android:741a333f8d42f26e19a49c',
    messagingSenderId: '431969184661',
    projectId: 'scanly-a1214',
    storageBucket: 'scanly-a1214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2HSccVssfTuhiEyFg_BE2I-Hit1HUWq4',
    appId: '1:431969184661:ios:f5db6b1625ed5d5619a49c',
    messagingSenderId: '431969184661',
    projectId: 'scanly-a1214',
    storageBucket: 'scanly-a1214.firebasestorage.app',
    iosBundleId: 'com.example.scanly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2HSccVssfTuhiEyFg_BE2I-Hit1HUWq4',
    appId: '1:431969184661:ios:f5db6b1625ed5d5619a49c',
    messagingSenderId: '431969184661',
    projectId: 'scanly-a1214',
    storageBucket: 'scanly-a1214.firebasestorage.app',
    iosBundleId: 'com.example.scanly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCErP8SBz4ExEvmv9kqCowbJCcAuF20q40',
    appId: '1:431969184661:web:9d659b4cdae74f5119a49c',
    messagingSenderId: '431969184661',
    projectId: 'scanly-a1214',
    authDomain: 'scanly-a1214.firebaseapp.com',
    storageBucket: 'scanly-a1214.firebasestorage.app',
    measurementId: 'G-ERNMZETRGM',
  );
}
